# Algoritmo eleiminação gaussiana

In [1]:
def eliminacaoGauss(a, b):
    n = len(a)
    for j in range(n - 1):
        for i in range(j + 1, n):
            m = a[i][j] / a[j][j]
            b[i] = b[i] - (m * b[j])

            for k in range(j, n):
                a[i][k] = a[i][k] - (m * a[j][k])
                
    return a, b

In [2]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

b = [7, 1, 4, 12]

u, c = eliminacaoGauss(a=a, b=b)
print(u, c)

[[2, 2, 1, 1], [0.0, -2.0, 1.5, -1.5], [0.0, 0.0, -5.25, -2.75], [0.0, 0.0, 0.0, 0.14285714285714285]] [7, -2.5, -5.25, 0.0]


### Algoritomo de substituição regressiva

In [3]:
import numpy as np

def substituicaoRegressiva(u, c):
    n = len(a)
    x = np.zeros((n))

    for i in reversed(range(n)):
        x[i] = c[i]
        for j in range(i + 1, n):
            x[i] = x[i] - (u[i][j] * x[j])

        x[i] = x[i]/u[i][i]

    return x

In [4]:
substituicaoRegressiva(u=u, c=c)

array([1., 2., 1., 0.])

# Pivotamento parcial

In [5]:
def permuteMax(a, col):
    maxPivoIndex = col
    for pivo in range(col, len(a)):
        if abs(a[pivo][col]) > abs(a[maxPivoIndex][col]):
            maxPivoIndex = pivo
            
            print("{} > {}".format(abs(a[pivo][col]), abs(a[maxPivoIndex][col])))

    maxList = a[maxPivoIndex]
    a[maxPivoIndex] = a[col]
    a[col] = maxList

    return a


a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

print(a)
for i in range(len(a) - 1):
    print(permuteMax(a, i))

[[2, 2, 1, 1], [1, -1, 2, -1], [3, 2, -3, -2], [4, 3, 2, 1]]
3 > 3
4 > 4
[[4, 3, 2, 1], [1, -1, 2, -1], [3, 2, -3, -2], [2, 2, 1, 1]]
2 > 2
[[4, 3, 2, 1], [3, 2, -3, -2], [1, -1, 2, -1], [2, 2, 1, 1]]
[[4, 3, 2, 1], [3, 2, -3, -2], [1, -1, 2, -1], [2, 2, 1, 1]]


In [6]:
def pivotamentoParcial(a, b):
    n = len(a)

    for j in range(n):

        a = permuteMax(a, j)

        for i in range(j + 1, n):
            m = a[i][j] / a[j][j]
            b[i] = b[i] - (m * b[j])

            for k in range(j, n):
                a[i][k] = a[i][k] - (m * a[j][k])
                
    return a, b

In [7]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

b = [7, 1, 4, 12]

u, c = pivotamentoParcial(a=a, b=b)

3 > 3
4 > 4


In [8]:
substituicaoRegressiva(u, c)

array([-80.66666667, 107.        ,  49.33333333, -90.        ])

# Metodo de Jacobi

In [3]:
import numpy as np

In [142]:
def diag_m(matriz):
    d = []
    m = np.array(matriz).copy()
    for i in range(len(matriz)):
        for j in range(len(matriz[i])):
            if i != j:
                m[i][j] = matriz[i][j]
            else:
                m[i][j] = 0
                d.append(matriz[i][j])
    return d, m

In [143]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

diag_m(a)

([2, -1, -3, 1],
 array([[ 0,  2,  1,  1],
        [ 1,  0,  2, -1],
        [ 3,  2,  0, -2],
        [ 4,  3,  2,  0]]))

In [192]:
def jacobi(a, b, maxIter, erro, x0):
    k = 0
    dr = erro + 1

    # pegando a diagonal princiapal e a matriz zerada a diagonal principal
    d, m = diag_m(a)

    # criando o vetor do mesmo tamanho de x0 para fazer as operações
    # e no final passar os valores para x0
    x = np.zeros((len(x0)))

    while k <= maxIter and dr > erro:
        k += 1

        for i in range(len(a)):
            # print("{} * {}".format(m[i], x0))
            dx = m[i] * x0
     
            x[i] = (b[i] - dx.sum()) / d[i]

        dr = np.array(abs(x - x0)).max()

        print(x, dr)

        # usando copy do numpy, pois somente passando x0 = x, o x0 estava pegando a referencia de x
        x0 = np.array(x).copy()

    return x0, dr
        

In [193]:
a = [[10, 2, -1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]

x0 = [0, 0, 0]

d, m = diag_m(a)

jacobi(a=a, b=b, maxIter=10, erro=0.01, x0=x0)

[ 0.7 -1.6  0.6] 1.6
[ 1.08 -1.86  0.94] 0.3800000000000001
[ 1.166 -2.004  0.942] 0.1439999999999999
[ 1.195  -2.0216  0.968 ] 0.028999999999999915
[ 1.20112 -2.0326   0.96748] 0.010999999999999677
[ 1.203268 -2.03372   0.969556] 0.0021480000000000388


(array([ 1.203268, -2.03372 ,  0.969556]), 0.0021480000000000388)