In [3]:
import numpy as np

# Algoritmo eliminação gaussiana

In [49]:
class EliminacaoGauss:
    def __init__(self, a, b):
        self.a = a
        self.b = b
        self.u, self.c = self.matrizTriangular()
        self.resolucao = self.substituicaoRegressiva()

    def matrizTriangular(self):
        """ Função que faz o cálculo de eliminação de gaus.
        a = matriz de entrada, b = vetor b. """

        #loop que percorre toda a matriz
        for j in range(len(self.a) - 1):
            for i in range(j + 1, len(self.a[j])):
                # representação de mij = aij/ajj
                m = self.a[i][j] / self.a[j][j]

                # representação de bi = bi - mij bj
                self.b[i] = self.b[i] - (m * self.b[j])

                # representação de aik = aik - mij ajk
                for k in range(j, len(self.a)):
                    self.a[i][k] = self.a[i][k] - (m * self.a[j][k])
        
        # retorna a matriz triangular com o vetor b, após
        # o cálculo da eliminação de gauss
        return self.a, self.b

    def substituicaoRegressiva(self):
        """ Função que faz o cálculo da substituição regressiva.
            u = matriz triangular, c = vetor b da saida da matriz
            triangular. """
            
        # define x com o mesmo tamnho do vetor c
        x = np.zeros((len(self.c)))

        # calculo da eliminação regressiva
        for i in reversed(range(len(self.u))):
            x[i] = self.c[i]
            for j in range(i + 1, len(self.u[i])):
                x[i] = x[i] - (self.u[i][j] * x[j])

            x[i] = x[i]/self.u[i][i]

        # retorna a solução do sistema no vetor,
        # onde o índice i representa o xi
        return x
    

### Testes

In [54]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

b = [7, 1, 4, 12]

eli = EliminacaoGauss(a, b)
print(eli.matrizTriangular())
print(eli.substituicaoRegressiva())

([[2, 2, 1, 1], [0.0, -2.0, 1.5, -1.5], [0.0, 0.0, -5.25, -2.75], [0.0, 0.0, 0.0, 0.14285714285714285]], [7, -2.5, -5.25, 0.0])
[1. 2. 1. 0.]


# Algoritmo pivotamento parcial

In [73]:
class PivotamentoParcial:
    def __init__(self, a, b):
        self.a = a
        self.b = b
        self.u, self. c = self.matrizTriangular()
        self.resolucao = self.substituicaoRegressiva()

    def permuteMax(self, col):
        """ Função responsável por fazer a permutação de uma determinada matriz
            com pivo o máximo, dado o indice da coluna do pivo
        """
        # pega o índice da coluna em que será feito o pivotamento
        maxPivoIndex = col

        # verifica qual o maior número do pivô
        for pivo in range(col, len(self.a)):
            if abs(self.a[pivo][col]) > abs(self.a[maxPivoIndex][col]):
                maxPivoIndex = pivo
                
                # print("{} > {}".format(abs(self.a[pivo][col]), abs(self.a[maxPivoIndex][col])))

        # fazendo a permutação
        maxList = self.a[maxPivoIndex]
        self.a[maxPivoIndex] = self.a[col]
        self.a[col] = maxList

        # retorna a matriz permutada
        return a

    def matrizTriangular(self):
        """ Função que calculo o pivotamento parcial, onde a = matriz e
            b = vetor b """
        # percorrendo a matriz
        for j in range(len(self.a)):

            # usando a função anterior para fazer a permutação
            a = self.permuteMax(j)

            # aplicando mesmo método de eliminação de gaus,
            # mas com a matriz permutada
            for i in range(j + 1, len(self.a[j])):
                m = self.a[i][j] / self.a[j][j]
                self.b[i] = self.b[i] - (m * self.b[j])

                for k in range(j, len(self.a)):
                    self.a[i][k] = self.a[i][k] - (m * self.a[j][k])

        # retorn a matriz triangular e o vetor b,
        # após o cálculo de pivotamento parcial
        return a, b

    def substituicaoRegressiva(self):
        """ Função que faz o cálculo da substituição regressiva.
            u = matriz triangular, c = vetor b da saida da matriz
            triangular. """
            
        # define x com o mesmo tamnho do vetor c
        x = np.zeros((len(self.c)))

        # calculo da eliminação regressiva
        for i in reversed(range(len(self.u))):
            x[i] = self.c[i]
            for j in range(i + 1, len(self.u[i])):
                x[i] = x[i] - (self.u[i][j] * x[j])

            x[i] = x[i]/self.u[i][i]

        # retorna a solução do sistema no vetor,
        # onde o índice i representa o xi
        return x

### Testes

In [74]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

b = [7, 1, 4, 12]

pivo = PivotamentoParcial(a, b)
pivo.resolucao

array([-80.66666667, 107.        ,  49.33333333, -90.        ])

# Algoritmo método de Jacobi

In [25]:
class Jacobi:
    def __init__(self, a, b, maxIter, erro, x0):
        self.a = a
        self.b = b
        self.maxIter = maxIter
        self.erro = erro
        self.x0 = x0
        
        # pegando a diagonal princiapal e a matriz zerada a diagonal principal
        self.d, self.m = self.diag_m()

        self.resolucao = self.jacobi()

    def diag_m(self):
        """ Função que retorna a diagonal principal e a matriz com a
            diagonal princial zerada. """
        # lista que será armazenada a diagonal principal da matriz
        d = []

        # copia a matriz para ficar com os mesmo elementos da
        # da matriz de entrada
        m = np.array(self.a).copy()

        # percorre a matriz
        for i in range(len(self.a)):
            for j in range(len(self.a[i])):
                # verifica se não está na matriz principal
                # caso não esteja, adiciona o elemento a matriz m
                if i != j:
                    m[i][j] = self.a[i][j]

                # caso seja da diagonal principal, appenda o valor
                # a lista de d e remove da matriz m
                else:
                    m[i][j] = 0
                    d.append(self.a[i][j])

        # retorna a diagonal principal e matriz zerada a diagonal principal
        return d, m

    def jacobi(self):
        """ Função que usa o método de jacobi para a resolução de um sistema
            linear. 
            a = matriz; b = vetor b; maxIter = máximo de iteração; erro = o erro
            a ser atingido como condição de parada; x0 = lista de valores para cada
            x. """
            
        k = 0
        dr = self.erro + 1

        # criando o vetor do mesmo tamanho de x0 para fazer as operações
        # e no final passar os valores para x0
        x = np.zeros((len(self.x0)))

        while k <= self.maxIter and dr > self.erro:
            k += 1

            for i in range(len(self.a)):
                # print("{} * {}".format(m[i], x0))
                # representação do cálculo de Mx0
                dx = self.m[i] * self.x0

                # representação de x = (b - Mx0) / D, onde Mx0 = dx do cálculo anterior 
                x[i] = (self.b[i] - dx.sum()) / self.d[i]

            # pegando o valor máximo do cálculo do erro de cada x
            dr = np.array(abs(x - self.x0)).max()

            # mostrando os valores de x e erro de cada iteração
            print(x, dr)

            # usando copy do numpy, pois somente passando x0 = x, o x0 estava pegando a referencia de x
            self.x0 = np.array(x).copy()

        # retorn o X da solução encontrada, o erro mínimo e o número de iteração
        return self.x0, dr, k

### Testes

In [26]:
a = [[10, 2, -1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]

x0 = [0, 0, 0]

jacobi = Jacobi(a=a, b=b, maxIter=10, erro=0.01, x0=x0)
jacobi.resolucao

[ 0.7 -1.6  0.6] 1.6
[ 1.08 -1.86  0.94] 0.3800000000000001
[ 1.166 -2.004  0.942] 0.1439999999999999
[ 1.195  -2.0216  0.968 ] 0.028999999999999915
[ 1.20112 -2.0326   0.96748] 0.010999999999999677
[ 1.203268 -2.03372   0.969556] 0.0021480000000000388


(array([ 1.203268, -2.03372 ,  0.969556]), 0.0021480000000000388, 6)

# Algoritmo método Gauss Seidel

In [33]:
class GaussSeidel:
    def __init__(self, a, b, maxIter, erro, x0):
        self.a = a
        self.b = b
        self.maxIter = maxIter
        self.erro = erro
        self.x0 = x0
        
        # pegando a diagonal princiapal e a matriz zerada a diagonal principal
        self.d, self.m = self.diag_m()

        self.resolucao = self.gaussSeidel()

    def diag_m(self):
        """ Função que retorna a diagonal principal e a matriz com a
            diagonal princial zerada. """
        # lista que será armazenada a diagonal principal da matriz
        d = []

        # copia a matriz para ficar com os mesmo elementos da
        # da matriz de entrada
        m = np.array(self.a).copy()

        # percorre a matriz
        for i in range(len(self.a)):
            for j in range(len(self.a[i])):
                # verifica se não está na matriz principal
                # caso não esteja, adiciona o elemento a matriz m
                if i != j:
                    m[i][j] = self.a[i][j]

                # caso seja da diagonal principal, appenda o valor
                # a lista de d e remove da matriz m
                else:
                    m[i][j] = 0
                    d.append(self.a[i][j])

        # retorna a diagonal principal e matriz zerada a diagonal principal
        return d, m

    def gaussSeidel(self):
        """ Cálculo do método de gauss-seidel para a resolução de um
            sistema linear. 
            a = matriz; b = vetor b; maxIter = máximo
            de iterações; erro = erro a ser atingido como método de parada;
            x0 = valores iniciais de x."""

        k = 0
        dr = self.erro + 1

        # matriz do tamanho de x0, para receber os valores
        x = np.zeros((len(self.x0)))

        # pegando os elementos pelo for, pois passando somente x = x0 pegava referencia, 
        # assim como a função copy tando do numpy quanto nativa do python
        for i in range(len(self.x0)):
            x[i] = self.x0[i]

        while k <= self.maxIter and dr > self.erro:
            k += 1

            for i in range(len(a)):
                # print("{} * {}".format(m[i], x0))
                # representação do cálculo de Mx
                dx = self.m[i] * x

                # representação de x = (b - Mx0) / D, onde Mx = dx do cálculo anterior 
                x[i] = (self.b[i] - dx.sum()) / self.d[i]

            # pegando o valor máximo do cálculo do erro de cada x
            dr = np.array(abs(x - self.x0)).max()

            # mostrando os valores de x e erro de cada iteração
            print(x, dr)

            # usando copy do numpy, pois somente passando x0 = x, o x0 estava pegando a referencia de x
            self.x0 = np.array(x).copy()

        # retorn o X da solução encontrada, o erro mínimo e o número de iteração
        return self.x0, dr, k
    

### Testes

In [37]:
a = [[10, 2, -1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]

x0 = [0, 0, 0]

seidel = GaussSeidel(a=a, b=b, maxIter=10, erro=0.001, x0=x0)
seidel.resolucao

[ 0.7   -1.74   0.982] 1.7399999999999998
[ 1.1462   -2.02564   0.978452] 0.44619999999999993
[ 1.2029732  -2.03628504  0.97029087] 0.05677320000000008
[ 1.2042861  -2.03491539  0.9696174 ] 0.0013696465600001595
[ 1.20394482 -2.03471244  0.96962477] 0.0003412766127999234


(array([ 1.20394482, -2.03471244,  0.96962477]), 0.0003412766127999234, 5)

# Atividade EPC-1

## 1. Resolva o sistema linear abaixo utilizando o método da eliminação de  Gauss: 

In [30]:
a = [[2, 2, 1, 1],
     [1, -1, 2, -1],
     [3, 2, -3, -2],
     [4, 3, 2, 1]]

b = [7, 1, 4, 12]

eliminacaoGauss(a=a, b=b)

([[2, 2, 1, 1],
  [0.0, -2.0, 1.5, -1.5],
  [0.0, 0.0, -5.25, -2.75],
  [0.0, 0.0, 0.0, 0.14285714285714285]],
 [7, -2.5, -5.25, 0.0])