# Algoritmo eleiminação gaussiana

In [1]:
def eliminacaoGauss(a, b):
    n = len(a)
    for j in range(n - 1):
        for i in range(j + 1, n):
            m = a[i][j] / a[j][j]
            b[i] = b[i] - (m * b[j])

            for k in range(j, n):
                a[i][k] = a[i][k] - (m * a[j][k])
                
    return a, b

In [2]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

b = [7, 1, 4, 12]

u, c = eliminacaoGauss(a=a, b=b)
print(u, c)

[[2, 2, 1, 1], [0.0, -2.0, 1.5, -1.5], [0.0, 0.0, -5.25, -2.75], [0.0, 0.0, 0.0, 0.14285714285714285]] [7, -2.5, -5.25, 0.0]


### Algoritomo de substituição regressiva

In [3]:
import numpy as np

def substituicaoRegressiva(u, c):
    n = len(a)
    x = np.zeros((n))

    for i in reversed(range(n)):
        x[i] = c[i]
        for j in range(i + 1, n):
            x[i] = x[i] - (u[i][j] * x[j])

        x[i] = x[i]/u[i][i]

    return x

In [4]:
substituicaoRegressiva(u=u, c=c)

array([1., 2., 1., 0.])

# Pivotamento parcial

In [5]:
def permuteMax(a, col):
    maxPivoIndex = col
    for pivo in range(col, len(a)):
        if abs(a[pivo][col]) > abs(a[maxPivoIndex][col]):
            maxPivoIndex = pivo
            
            print("{} > {}".format(abs(a[pivo][col]), abs(a[maxPivoIndex][col])))

    maxList = a[maxPivoIndex]
    a[maxPivoIndex] = a[col]
    a[col] = maxList

    return a


a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

print(a)
for i in range(len(a) - 1):
    print(permuteMax(a, i))

[[2, 2, 1, 1], [1, -1, 2, -1], [3, 2, -3, -2], [4, 3, 2, 1]]
3 > 3
4 > 4
[[4, 3, 2, 1], [1, -1, 2, -1], [3, 2, -3, -2], [2, 2, 1, 1]]
2 > 2
[[4, 3, 2, 1], [3, 2, -3, -2], [1, -1, 2, -1], [2, 2, 1, 1]]
[[4, 3, 2, 1], [3, 2, -3, -2], [1, -1, 2, -1], [2, 2, 1, 1]]


In [6]:
def pivotamentoParcial(a, b):
    n = len(a)

    for j in range(n):

        a = permuteMax(a, j)

        for i in range(j + 1, n):
            m = a[i][j] / a[j][j]
            b[i] = b[i] - (m * b[j])

            for k in range(j, n):
                a[i][k] = a[i][k] - (m * a[j][k])
                
    return a, b

In [7]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

b = [7, 1, 4, 12]

u, c = pivotamentoParcial(a=a, b=b)

3 > 3
4 > 4


In [8]:
substituicaoRegressiva(u, c)

array([-80.66666667, 107.        ,  49.33333333, -90.        ])

# Metodo de Jacobi

In [29]:
def diag_m(matriz):
    d = []
    m = np.array(matriz).copy()
    for i in range(len(matriz)):
        for j in range(len(matriz[i])):
            if i != j:
                m[i][j] = matriz[i][j]
            else:
                m[i][j] = 0
                d.append(matriz[i][j])
        
    return np.array(d), m

In [30]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

diag_m(a)

(array([ 2, -1, -3,  1]),
 array([[ 0,  2,  1,  1],
        [ 1,  0,  2, -1],
        [ 3,  2,  0, -2],
        [ 4,  3,  2,  0]]))

In [54]:
def jacobi(a, b, maxIter, erro, x0):
    k = 0
    dr = erro + 1
    d, m = diag_m(a)

    print(a, b, maxIter, erro, x0)

    while (k <= maxIter) and (dr > erro):
        k = k + 1

        x = (b -  (m * x0)) / d

        dr = abs(x[0] - x0)/abs(x[0])

        x0 = x[0]

    return x0
        

In [55]:
a = [[10, 2, -1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]

x0 = [0, 0, 0]

d, m = diag_m(a)

jacobi(a=a, b=b, maxIter=10, erro=0.01, x0=x0)

# print("diagonal: ", d)
# print("m: ", m)

# x = (b -  (m * x0)) / d

# abs(x[0] - x0)/abs(x[0])

[[10, 2, -1], [1, 5, 1], [2, 3, 10]] [7, -8, 6] 10 0.01 [0, 0, 0]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()