# Algoritmo eleiminação gaussiana

In [17]:
def eliminacaoGauss(a, b):

    #loop que percorre toda a matriz
    for j in range(len(a) - 1):
        for i in range(j + 1, len(a[j])):
            # representação de mij = aij/ajj
            m = a[i][j] / a[j][j]

            # representação de bi = bi - mij bj
            b[i] = b[i] - (m * b[j])

            # representação de aik = aik - mij ajk
            for k in range(j, len(a)):
                a[i][k] = a[i][k] - (m * a[j][k])
    
    # retorna a matriz triangular com o vetor b, após
    # o cálculo da eliminação de gauss
    return a, b

In [18]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

b = [7, 1, 4, 12]

u, c = eliminacaoGauss(a=a, b=b)
print(u, c)

[[2, 2, 1, 1], [0.0, -2.0, 1.5, -1.5], [0.0, 0.0, -5.25, -2.75], [0.0, 0.0, 0.0, 0.14285714285714285]] [7, -2.5, -5.25, 0.0]


### Algoritomo de substituição regressiva

In [19]:
import numpy as np

def substituicaoRegressiva(u, c):
    # define x com o mesmo tamnho do vetor c
    x = np.zeros((len(c)))

    # calculo da eliminação regressiva
    for i in reversed(range(len(u))):
        x[i] = c[i]
        for j in range(i + 1, len(u[i])):
            x[i] = x[i] - (u[i][j] * x[j])

        x[i] = x[i]/u[i][i]

    # retorna a solução do sistema no vetor,
    # onde o índice i representa o xi
    return x

In [20]:
substituicaoRegressiva(u=u, c=c)

array([1., 2., 1., 0.])

# Pivotamento parcial

In [21]:
def permuteMax(a, col):
    # pega o índice da coluna em que será feito o pivotamento
    maxPivoIndex = col

    # verifica qual o maior número do pivô
    for pivo in range(col, len(a)):
        if abs(a[pivo][col]) > abs(a[maxPivoIndex][col]):
            maxPivoIndex = pivo
            
            print("{} > {}".format(abs(a[pivo][col]), abs(a[maxPivoIndex][col])))

    # fazendo a permutação
    maxList = a[maxPivoIndex]
    a[maxPivoIndex] = a[col]
    a[col] = maxList

    # retorna a matriz permutada
    return a


a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

print(a)
for i in range(len(a) - 1):
    print(permuteMax(a, i))

[[2, 2, 1, 1], [1, -1, 2, -1], [3, 2, -3, -2], [4, 3, 2, 1]]
3 > 3
4 > 4
[[4, 3, 2, 1], [1, -1, 2, -1], [3, 2, -3, -2], [2, 2, 1, 1]]
2 > 2
[[4, 3, 2, 1], [3, 2, -3, -2], [1, -1, 2, -1], [2, 2, 1, 1]]
[[4, 3, 2, 1], [3, 2, -3, -2], [1, -1, 2, -1], [2, 2, 1, 1]]


In [22]:
def pivotamentoParcial(a, b):
    # percorrendo a matriz
    for j in range(len(a)):

        # usando a função anterior para fazer a permutação
        a = permuteMax(a, j)

        # aplicando mesmo método de eliminação de gaus,
        # mas com a matriz permutada
        for i in range(j + 1, len(a[j])):
            m = a[i][j] / a[j][j]
            b[i] = b[i] - (m * b[j])

            for k in range(j, len(a)):
                a[i][k] = a[i][k] - (m * a[j][k])

    # retorn a matriz triangular e o vetor b,
    # após o cálculo de pivotamento parcial
    return a, b

In [23]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

b = [7, 1, 4, 12]

u, c = pivotamentoParcial(a=a, b=b)
u, c

3 > 3
4 > 4


([[4, 3, 2, 1],
  [0.0, -1.75, 1.5, -1.25],
  [0.0, 0.0, -4.714285714285714, -2.5714285714285716],
  [0.0, 0.0, 0.0, -0.09090909090909086]],
 [7, -0.75, -1.1428571428571428, 8.181818181818183])

In [24]:
substituicaoRegressiva(u, c)

array([-80.66666667, 107.        ,  49.33333333, -90.        ])

# Metodo de Jacobi

In [25]:
import numpy as np

In [6]:
def diag_m(matriz):
    # lista que será armazenada a diagonal principal da matriz
    d = []

    # copia a matriz para ficar com os mesmo elementos da
    # da matriz de entrada
    m = np.array(matriz).copy()

    # percorre a matriz
    for i in range(len(matriz)):
        for j in range(len(matriz[i])):
            # verifica se não está na matriz principal
            # caso não esteja, adiciona o elemento a matriz m
            if i != j:
                m[i][j] = matriz[i][j]

            # caso seja da diagonal principal, appenda o valor
            # a lista de d e remove da matriz m
            else:
                m[i][j] = 0
                d.append(matriz[i][j])

    # retorna a diagonal principal e matriz zerada a diagonal principal
    return d, m

In [143]:
a = [[2, 2, 1, 1],
    [1, -1, 2, -1],
    [3, 2, -3, -2],
    [4, 3, 2, 1]]

diag_m(a)

([2, -1, -3, 1],
 array([[ 0,  2,  1,  1],
        [ 1,  0,  2, -1],
        [ 3,  2,  0, -2],
        [ 4,  3,  2,  0]]))

In [48]:
def jacobi(a, b, maxIter, erro, x0):
    k = 0
    dr = erro + 1

    # pegando a diagonal princiapal e a matriz zerada a diagonal principal
    d, m = diag_m(a)

    # criando o vetor do mesmo tamanho de x0 para fazer as operações
    # e no final passar os valores para x0
    x = np.zeros((len(x0)))

    while k <= maxIter and dr > erro:
        k += 1

        for i in range(len(a)):
            # print("{} * {}".format(m[i], x0))
            # representação do cálculo de Mx0
            dx = m[i] * x0

            # representação de x = (b - Mx0) / D, onde Mx0 = dx do cálculo anterior 
            x[i] = (b[i] - dx.sum()) / d[i]

        # pegando o valor máximo do cálculo do erro de cada x
        dr = np.array(abs(x - x0)).max()

        # mostrando os valores de x e erro de cada iteração
        print(x, dr)

        # usando copy do numpy, pois somente passando x0 = x, o x0 estava pegando a referencia de x
        x0 = np.array(x).copy()

    # retorn o X da solução encontrada, o erro mínimo e o número de iteração
    return x0, dr, k
        

In [49]:
a = [[10, 2, -1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]

x0 = [0, 0, 0]

d, m = diag_m(a)

jacobi(a=a, b=b, maxIter=10, erro=0.01, x0=x0)

[ 0.7 -1.6  0.6] 1.6
[ 1.08 -1.86  0.94] 0.3800000000000001
[ 1.166 -2.004  0.942] 0.1439999999999999
[ 1.195  -2.0216  0.968 ] 0.028999999999999915
[ 1.20112 -2.0326   0.96748] 0.010999999999999677
[ 1.203268 -2.03372   0.969556] 0.0021480000000000388


(array([ 1.203268, -2.03372 ,  0.969556]), 0.0021480000000000388, 6)

In [50]:
def gaussSidel(a, b, maxIter, erro, x0):
    k = 0
    dr = erro + 1

    # pegando a diagonal princiapal e a matriz zerada a diagonal principal
    d, m = diag_m(a)

    # matriz do tamanho de x0, para receber os valores
    x = np.zeros((len(x0)))

    # pegando os elementos pelo for, pois passando somente x = x0 pegava referencia, 
    # assim como a função copy tando do numpy quanto nativa do python
    for i in range(len(x0)):
        x[i] = x0[i]

    while k <= maxIter and dr > erro:
        k += 1

        for i in range(len(a)):
            # print("{} * {}".format(m[i], x0))
            # representação do cálculo de Mx
            dx = m[i] * x

            # representação de x = (b - Mx0) / D, onde Mx = dx do cálculo anterior 
            x[i] = (b[i] - dx.sum()) / d[i]

        # pegando o valor máximo do cálculo do erro de cada x
        dr = np.array(abs(x - x0)).max()

        # mostrando os valores de x e erro de cada iteração
        print(x, dr)

        # usando copy do numpy, pois somente passando x0 = x, o x0 estava pegando a referencia de x
        x0 = np.array(x).copy()

    # retorn o X da solução encontrada, o erro mínimo e o número de iteração
    return x0, dr, k

In [51]:
a = [[10, 2, -1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]

x0 = [0, 0, 0]

gaussSidel(a=a, b=b, x0=x0, maxIter=10, erro=0.001)

[ 0.7   -1.74   0.982] 1.7399999999999998
[ 1.1462   -2.02564   0.978452] 0.44619999999999993
[ 1.2029732  -2.03628504  0.97029087] 0.05677320000000008
[ 1.2042861  -2.03491539  0.9696174 ] 0.0013696465600001595
[ 1.20394482 -2.03471244  0.96962477] 0.0003412766127999234


(array([ 1.20394482, -2.03471244,  0.96962477]), 0.0003412766127999234, 5)